from __future__ import annotations

from tutor import hooks


# External S3-compatible object storage for Kubernetes deployments.
# This plugin configures Open edX to use an already-provisioned MinIO service;
# it intentionally does NOT create MinIO containers, Kubernetes Deployments,
# Services, PVCs, buckets, or MinIO users.
hooks.Filters.CONFIG_DEFAULTS.add_items([
    ("FPT_MINIO_ENABLED", False),
    ("FPT_MINIO_ENDPOINT", ""),
    ("FPT_MINIO_BUCKET_NAME", "openedx"),
    ("FPT_MINIO_FILE_UPLOAD_BUCKET_NAME", "openedxuploads"),
    ("FPT_MINIO_VIDEO_UPLOAD_BUCKET_NAME", "openedxvideos"),
    ("FPT_MINIO_GRADES_BUCKET_NAME", "openedxgrades"),
    ("FPT_MINIO_OPENEDX_LEARNING_BUCKET_NAME", "openedxlearning"),
    ("FPT_MINIO_QUERYSTRING_AUTH", True),
])


# Credentials are provided by Tutor core via OPENEDX_AWS_ACCESS_KEY and
# OPENEDX_AWS_SECRET_ACCESS_KEY. Add only the S3 bucket/runtime tokens that
# django-storages expects.
hooks.Filters.ENV_PATCHES.add_item((
    "openedx-auth",
    """
{% if FPT_MINIO_ENABLED %}
# FPT_EXTERNAL_MINIO_V1
AWS_STORAGE_BUCKET_NAME: "{{ FPT_MINIO_BUCKET_NAME }}"
AWS_S3_CUSTOM_DOMAIN: ""
AWS_QUERYSTRING_AUTH: {% if FPT_MINIO_QUERYSTRING_AUTH %}true{% else %}false{% endif %}
{% endif %}
""",
))


# Mirror the Open edX storage wiring used by Tutor MinIO, but target an
# external endpoint and never add a MinIO workload to Kubernetes.
hooks.Filters.ENV_PATCHES.add_item((
    "openedx-common-settings",
    """
{% if FPT_MINIO_ENABLED %}
# FPT_EXTERNAL_MINIO_V1
STORAGES["default"]["BACKEND"] = "storages.backends.s3boto3.S3Boto3Storage"

VIDEO_IMAGE_SETTINGS["STORAGE_KWARGS"]["location"] = VIDEO_IMAGE_SETTINGS["STORAGE_KWARGS"]["location"].lstrip("/")
VIDEO_TRANSCRIPTS_SETTINGS["STORAGE_KWARGS"]["location"] = VIDEO_TRANSCRIPTS_SETTINGS["STORAGE_KWARGS"]["location"].lstrip("/")

GRADES_DOWNLOAD["STORAGE_KWARGS"] = {
    "location": GRADES_DOWNLOAD["STORAGE_KWARGS"]["location"].lstrip("/"),
    "bucket_name": "{{ FPT_MINIO_GRADES_BUCKET_NAME }}",
}

OPENEDX_LEARNING["MEDIA"]["BACKEND"] = STORAGES["default"]["BACKEND"]
OPENEDX_LEARNING["MEDIA"]["OPTIONS"] = {
    "bucket_name": "{{ FPT_MINIO_OPENEDX_LEARNING_BUCKET_NAME }}",
}

# ORA2 learner uploads
ORA2_FILEUPLOAD_BACKEND = "s3"
FILE_UPLOAD_STORAGE_BUCKET_NAME = "{{ FPT_MINIO_FILE_UPLOAD_BUCKET_NAME }}"

AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ENDPOINT_URL = "{{ FPT_MINIO_ENDPOINT }}"
AWS_S3_ADDRESSING_STYLE = "path"
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_EXPIRE = 7 * 24 * 60 * 60

from botocore.client import Config as BotoConfig
AWS_S3_CLIENT_CONFIG = BotoConfig(
    request_checksum_calculation="when_required",
    response_checksum_validation="when_required",
    signature_version="s3v4",
    s3={"addressing_style": "path"},
)
{% endif %}
""",
))


# Course import/export artifacts must also be shared object storage so any CMS
# pod can serve a task started by another pod.
hooks.Filters.ENV_PATCHES.add_item((
    "openedx-cms-common-settings",
    """
{% if FPT_MINIO_ENABLED %}
# FPT_EXTERNAL_MINIO_V1
COURSE_IMPORT_EXPORT_STORAGE = USER_TASKS_ARTIFACT_STORAGE
{% endif %}
""",
))


# Profile images are generated by the LMS and must be shared across replicas.
hooks.Filters.ENV_PATCHES.add_item((
    "openedx-lms-production-settings",
    """
{% if FPT_MINIO_ENABLED %}
# FPT_EXTERNAL_MINIO_V1
PROFILE_IMAGE_BACKEND = {
    "class": STORAGES["default"]["BACKEND"],
    "options": {
        "bucket_name": "{{ FPT_MINIO_BUCKET_NAME }}",
        "querystring_auth": False,
        "location": PROFILE_IMAGE_BACKEND["options"]["location"].lstrip("/"),
    },
}
{% endif %}
""",
))
