"""Tutor integration for the Open edX <-> ACMS / AI Server connector.

This production plugin intentionally owns both pieces of the integration:
1. Install the Django connector package into the shared Open edX image.
2. Render the connector security/runtime settings into BOTH LMS and CMS.

ACMS 25.9.16.7.2.64.16.5.7.2.10 uses the canonical
/api/ai-connector/v1/* namespace. Student Management runtime endpoints are served
from LMS Django, while Studio draft/publish/session-bridge endpoints are served
from CMS Django. Therefore HMAC must be configured on both applications.

Secrets are deliberately empty by default. Production must provide the same HMAC
secret used by AI Server OPENEDX_CONNECTOR_HMAC_SECRET via Tutor config.
"""

from tutor import hooks


hooks.Filters.CONFIG_DEFAULTS.add_items([
    ("AI_CONNECTOR_PUBLISH_USERNAME", ""),
    ("AI_CONNECTOR_ALLOW_ANONYMOUS_PUBLISH", "false"),
    ("AI_CONNECTOR_HMAC_SECRET", ""),
    ("AI_CONNECTOR_HMAC_SKEW_SECONDS", "300"),
    ("AI_CONNECTOR_ALLOWED_DOWNLOAD_HOSTS", "cms.fpl.edu.vn,scms.fpl.edu.vn,edx.cms.fpl.edu.vn,app.cms.fpl.edu.vn"),
    ("AI_CONNECTOR_COMPONENT_PUBLISH_ENABLED", "false"),
    ("AI_CONNECTOR_TAGGING_ENABLED", "true"),
    ("AI_CONNECTOR_TAG_TAXONOMY_EXPORT_ID", "ai-learning-check"),
    ("AI_CONNECTOR_TAG_TAXONOMY_NAME", "AI Learning Check"),
    ("AI_CONNECTOR_TAG_TAXONOMY_DESCRIPTION", "Tags automatically assigned by AI Learning Check Generator."),
    ("AI_CONNECTOR_AUTO_CREATE_ORG", "false"),
    ("AI_CONNECTOR_POST_PUBLISH_EVENTS_ENABLED", "false"),
    ("AI_CONNECTOR_ADMIN_GROUPS", "AI_ADMIN,AI Admin"),
    ("AI_CONNECTOR_ALLOW_ADMIN_GROUP", "false"),

    # Unified Student Management connector contract.
    ("AI_CONNECTOR_MAX_BATCH_SIZE", "5000"),
    ("AI_CONNECTOR_DEFAULT_ENROLLMENT_MODE", "audit"),
    ("AI_CONNECTOR_CREATED_USER_PASSWORD_MODE", "unusable"),
    ("AI_CONNECTOR_CREATED_USER_DEFAULT_PASSWORD", ""),

    # CMS -> ACMS browser session bridge. The bridge secret may be left empty;
    # connector code then falls back to AI_CONNECTOR_HMAC_SECRET.
    ("AI_CONNECTOR_SESSION_BRIDGE_SECRET", ""),
    ("AI_CONNECTOR_SESSION_BRIDGE_ALLOWED_RETURN_HOSTS", "dash-cms.fpl.edu.vn"),
    ("AI_CONNECTOR_SESSION_BRIDGE_TTL_SECONDS", "60"),
    ("AI_CONNECTOR_SESSION_BRIDGE_ISSUER", "openedx-ai-connector"),
    ("AI_CONNECTOR_SESSION_BRIDGE_AUDIENCE", "ai-learning-server"),
    ("AI_CONNECTOR_ALLOW_LOCAL_BRIDGE_RETURN", "false"),
    ("AI_CONNECTOR_DEBUG_ERRORS", "false"),

    # Deprecated /api/ai-student-insight/v1 compatibility. Do not maintain a
    # second secret; generated settings below alias the old values to connector.
    ("AI_STUDENT_INSIGHT_SHARED_SECRET", ""),
    ("AI_STUDENT_INSIGHT_HMAC_SKEW_SECONDS", "300"),
    ("AI_STUDENT_INSIGHT_MAX_BATCH_SIZE", ""),

    ("AI_QUIZ_RUNTIME_ALLOWED_ORIGINS", "https://cms.fpl.edu.vn,https://scms.fpl.edu.vn,https://edx.cms.fpl.edu.vn,https://app.cms.fpl.edu.vn,https://dash-cms.fpl.edu.vn"),
])


_COMMON_CONNECTOR_SETTINGS = r'''
# FPT ACMS / Open edX Connector settings
# Generated by Tutor plugin: openedx_connector
AI_CONNECTOR_PUBLISH_USERNAME = "{{ AI_CONNECTOR_PUBLISH_USERNAME }}"
AI_CONNECTOR_ALLOW_ANONYMOUS_PUBLISH = "{{ AI_CONNECTOR_ALLOW_ANONYMOUS_PUBLISH }}"
AI_CONNECTOR_HMAC_SECRET = "{{ AI_CONNECTOR_HMAC_SECRET }}"
AI_CONNECTOR_HMAC_SKEW_SECONDS = "{{ AI_CONNECTOR_HMAC_SKEW_SECONDS }}"
AI_CONNECTOR_ALLOWED_DOWNLOAD_HOSTS = "{{ AI_CONNECTOR_ALLOWED_DOWNLOAD_HOSTS }}"
AI_CONNECTOR_COMPONENT_PUBLISH_ENABLED = "{{ AI_CONNECTOR_COMPONENT_PUBLISH_ENABLED }}"
AI_CONNECTOR_TAGGING_ENABLED = "{{ AI_CONNECTOR_TAGGING_ENABLED }}"
AI_CONNECTOR_TAG_TAXONOMY_EXPORT_ID = "{{ AI_CONNECTOR_TAG_TAXONOMY_EXPORT_ID }}"
AI_CONNECTOR_TAG_TAXONOMY_NAME = "{{ AI_CONNECTOR_TAG_TAXONOMY_NAME }}"
AI_CONNECTOR_TAG_TAXONOMY_DESCRIPTION = "{{ AI_CONNECTOR_TAG_TAXONOMY_DESCRIPTION }}"
AI_CONNECTOR_AUTO_CREATE_ORG = "{{ AI_CONNECTOR_AUTO_CREATE_ORG }}"
AI_CONNECTOR_POST_PUBLISH_EVENTS_ENABLED = "{{ AI_CONNECTOR_POST_PUBLISH_EVENTS_ENABLED }}"
AI_CONNECTOR_ADMIN_GROUPS = "{{ AI_CONNECTOR_ADMIN_GROUPS }}"
AI_CONNECTOR_ALLOW_ADMIN_GROUP = "{{ AI_CONNECTOR_ALLOW_ADMIN_GROUP }}"
AI_CONNECTOR_MAX_BATCH_SIZE = "{{ AI_CONNECTOR_MAX_BATCH_SIZE }}"
AI_CONNECTOR_DEFAULT_ENROLLMENT_MODE = "{{ AI_CONNECTOR_DEFAULT_ENROLLMENT_MODE }}"
AI_CONNECTOR_CREATED_USER_PASSWORD_MODE = "{{ AI_CONNECTOR_CREATED_USER_PASSWORD_MODE }}"
AI_CONNECTOR_CREATED_USER_DEFAULT_PASSWORD = "{{ AI_CONNECTOR_CREATED_USER_DEFAULT_PASSWORD }}"
AI_CONNECTOR_SESSION_BRIDGE_SECRET = "{{ AI_CONNECTOR_SESSION_BRIDGE_SECRET }}"
AI_CONNECTOR_SESSION_BRIDGE_ALLOWED_RETURN_HOSTS = "{{ AI_CONNECTOR_SESSION_BRIDGE_ALLOWED_RETURN_HOSTS }}"
AI_CONNECTOR_SESSION_BRIDGE_TTL_SECONDS = "{{ AI_CONNECTOR_SESSION_BRIDGE_TTL_SECONDS }}"
AI_CONNECTOR_SESSION_BRIDGE_ISSUER = "{{ AI_CONNECTOR_SESSION_BRIDGE_ISSUER }}"
AI_CONNECTOR_SESSION_BRIDGE_AUDIENCE = "{{ AI_CONNECTOR_SESSION_BRIDGE_AUDIENCE }}"
AI_CONNECTOR_ALLOW_LOCAL_BRIDGE_RETURN = "{{ AI_CONNECTOR_ALLOW_LOCAL_BRIDGE_RETURN }}"
AI_CONNECTOR_DEBUG_ERRORS = "{{ AI_CONNECTOR_DEBUG_ERRORS }}"
AI_QUIZ_RUNTIME_ALLOWED_ORIGINS = "{{ AI_QUIZ_RUNTIME_ALLOWED_ORIGINS }}"

# Deprecated aliases retained for rolling upgrades only.
AI_STUDENT_INSIGHT_SHARED_SECRET = "{{ AI_STUDENT_INSIGHT_SHARED_SECRET }}" or AI_CONNECTOR_HMAC_SECRET
AI_STUDENT_INSIGHT_HMAC_SKEW_SECONDS = "{{ AI_STUDENT_INSIGHT_HMAC_SKEW_SECONDS }}"
AI_STUDENT_INSIGHT_MAX_BATCH_SIZE = "{{ AI_STUDENT_INSIGHT_MAX_BATCH_SIZE }}" or AI_CONNECTOR_MAX_BATCH_SIZE
AI_STUDENT_INSIGHT_DEFAULT_ENROLLMENT_MODE = AI_CONNECTOR_DEFAULT_ENROLLMENT_MODE
'''


# Studio/CMS handles draft content, publish and the CMS session bridge.
hooks.Filters.ENV_PATCHES.add_item(("openedx-cms-common-settings", _COMMON_CONNECTOR_SETTINGS))

# LMS handles Student Management runtime APIs such as users/resolve,
# course-enrollment/enroll and class-analytics. HMAC MUST be present here too.
hooks.Filters.ENV_PATCHES.add_item(("openedx-lms-common-settings", _COMMON_CONNECTOR_SETTINGS))


hooks.Filters.ENV_PATCHES.add_item((
    "openedx-dockerfile-pre-assets",
    """
# Install Open edX Connector Plugin during openedx image build
RUN $PIP_COMMAND install -e /openedx/edx-platform/openedx_connector_plugin
""",
))
