from django.urls import path

from .views import (
    health,
    course_content,
    studio_course_content,
    publish_problem,
    ensure_chapter_library,
    import_problem_to_library,
    publish_diagnostics,
    backfill_library_tags,
    library_tags_diagnostics,
    verify_library_problem,
    delete_library_problem,
    session_me,
    session_bridge,
    create_quiz_node, delete_quiz_node,
    insert_problem_banks,
)
from .student_insight import (
    student_insight_resolve_users,
    student_insight_course_search,
    student_insight_class_analytics,
    student_insight_course_enrollment_batch,
    student_insight_course_enrollment_enroll,
    student_insight_course_enrollment_remove,
    student_insight_course_progress_batch,
    student_insight_quiz_grades_batch,
)

# NOTE:
# Canonical runtime prefix is /api/ai-connector/v1/.
# OpenEdxAIConnectorConfig also mounts the old /api/ai-student-insight/v1/
# alias for rolling upgrades only. Therefore paths here must be RELATIVE.
urlpatterns = [
    path("users/resolve", student_insight_resolve_users, name="student_insight_resolve_users"),
    path("users/resolve/", student_insight_resolve_users, name="student_insight_resolve_users_slash"),
    path("courses/search", student_insight_course_search, name="student_insight_course_search"),
    path("courses/search/", student_insight_course_search, name="student_insight_course_search_slash"),
    path("class-analytics", student_insight_class_analytics, name="student_insight_class_analytics"),
    path("class-analytics/", student_insight_class_analytics, name="student_insight_class_analytics_slash"),
    path("course-enrollment/batch", student_insight_course_enrollment_batch, name="student_insight_course_enrollment_batch"),
    path("course-enrollment/enroll", student_insight_course_enrollment_enroll, name="student_insight_course_enrollment_enroll"),
    path("course-enrollment/remove", student_insight_course_enrollment_remove, name="student_insight_course_enrollment_remove"),
    path("course-enrollment/batch/", student_insight_course_enrollment_batch, name="student_insight_course_enrollment_batch_slash"),
    path("course-enrollment/enroll/", student_insight_course_enrollment_enroll, name="student_insight_course_enrollment_enroll_slash"),
    path("course-enrollment/remove/", student_insight_course_enrollment_remove, name="student_insight_course_enrollment_remove_slash"),
    path("course-progress/batch", student_insight_course_progress_batch, name="student_insight_course_progress_batch"),
    path("course-progress/batch/", student_insight_course_progress_batch, name="student_insight_course_progress_batch_slash"),
    path("quiz-grades/batch", student_insight_quiz_grades_batch, name="student_insight_quiz_grades_batch"),
    path("quiz-grades/batch/", student_insight_quiz_grades_batch, name="student_insight_quiz_grades_batch_slash"),
    path("health", health, name="ai_connector_health"),
    path("health/", health, name="ai_connector_health_slash"),
    path("session/me", session_me, name="ai_connector_session_me"),
    path("session/me/", session_me, name="ai_connector_session_me_slash"),
    path("session/bridge", session_bridge, name="ai_connector_session_bridge"),
    path("session/bridge/", session_bridge, name="ai_connector_session_bridge_slash"),
    path("publish-diagnostics", publish_diagnostics, name="ai_connector_publish_diagnostics"),
    path("publish-diagnostics/", publish_diagnostics, name="ai_connector_publish_diagnostics_slash"),
    path("courses/<path:course_id>/content", course_content, name="ai_connector_course_content"),
    path("courses/<path:course_id>/studio-content", studio_course_content, name="ai_connector_studio_content"),
    path("courses/<path:course_id>/problems", publish_problem, name="ai_connector_publish_problem"),
    path("courses/<path:course_id>/libraries", ensure_chapter_library, name="ai_connector_ensure_chapter_library"),
    path("courses/<path:course_id>/quiz-nodes", create_quiz_node, name="ai_connector_create_quiz_node"),
    path("courses/<path:course_id>/quiz-nodes/", create_quiz_node, name="ai_connector_create_quiz_node_slash"),
    path("courses/<path:course_id>/quiz-nodes/delete", delete_quiz_node, name="ai_connector_delete_quiz_node"),
    path("courses/<path:course_id>/quiz-nodes/delete/", delete_quiz_node, name="ai_connector_delete_quiz_node_slash"),
    path("courses/<path:course_id>/problem-banks", insert_problem_banks, name="ai_connector_insert_problem_banks"),
    path("courses/<path:course_id>/problem-banks/", insert_problem_banks, name="ai_connector_insert_problem_banks_slash"),
    path("libraries/<path:library_key>/problems", import_problem_to_library, name="ai_connector_import_problem_to_library"),
    path("libraries/<path:library_key>/backfill-tags", backfill_library_tags, name="ai_connector_backfill_library_tags"),
    path("libraries/<path:library_key>/backfill-tags/", backfill_library_tags, name="ai_connector_backfill_library_tags_slash"),
    path("libraries/<path:library_key>/tags/diagnostics", library_tags_diagnostics, name="ai_connector_library_tags_diagnostics"),
    path("libraries/<path:library_key>/tags/diagnostics/", library_tags_diagnostics, name="ai_connector_library_tags_diagnostics_slash"),
    path("libraries/<path:library_key>/problems/verify", verify_library_problem, name="ai_connector_verify_library_problem"),
    path("libraries/<path:library_key>/problems/verify/", verify_library_problem, name="ai_connector_verify_library_problem_slash"),
    path("libraries/<path:library_key>/problems/delete", delete_library_problem, name="ai_connector_delete_library_problem"),
    path("libraries/<path:library_key>/problems/delete/", delete_library_problem, name="ai_connector_delete_library_problem_slash"),
]
