# Generated by ChatGPT for v0.4.0 custom timed practice quiz.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openedx_unit_reset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitQuizTimerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('sequence_usage_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('unit_usage_key', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, default='Quiz tự luyện', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('duration_seconds', models.PositiveIntegerField(default=900)),
                ('cooldown_seconds', models.PositiveIntegerField(default=300)),
                ('auto_submit_on_timeout', models.BooleanField(default=True)),
                ('lock_after_timeout', models.BooleanField(default=True)),
                ('native_timed_exam', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitQuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('sequence_usage_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('unit_usage_key', models.CharField(db_index=True, max_length=255)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('duration_seconds', models.PositiveIntegerField(default=900)),
                ('cooldown_seconds', models.PositiveIntegerField(default=300)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=32)),
                ('auto_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('reset_available_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timeout_payload', models.JSONField(blank=True, default=dict)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='openedx_unit_reset.unitquiztimerconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='unitquiztimerconfig',
            unique_together={('course_id', 'unit_usage_key')},
        ),
        migrations.AddIndex(
            model_name='unitquiztimerconfig',
            index=models.Index(fields=['course_id', 'unit_usage_key'], name='unit_quiz_cfg_course_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='unitquiztimerconfig',
            index=models.Index(fields=['course_id', 'sequence_usage_key'], name='unit_quiz_cfg_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='unitquiztimerconfig',
            index=models.Index(fields=['enabled'], name='unit_quiz_cfg_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='unitquizsession',
            index=models.Index(fields=['user', 'course_id', 'unit_usage_key', 'status'], name='unit_quiz_sess_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unitquizsession',
            index=models.Index(fields=['course_id', 'unit_usage_key', 'status'], name='unit_quiz_sess_unit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unitquizsession',
            index=models.Index(fields=['expires_at', 'status'], name='unit_quiz_sess_exp_status_idx'),
        ),
    ]
